# Generated by Django 4.1.3 on 2022-11-11 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contactapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category", options={"verbose_name_plural": "Categories"},
        ),
    ]
