# Generated by Django 4.1.3 on 2022-11-11 01:04

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("contactapp", "0002_alter_category_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profile", options={"ordering": ["favorites"]},
        ),
        migrations.AlterField(
            model_name="profile",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, region=None, unique=True
            ),
        ),
    ]
