# Generated by Django 4.1.3 on 2022-11-11 19:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contactapp", "0003_alter_profile_options_alter_profile_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="contact_image",
            field=models.ImageField(
                default=datetime.datetime(
                    2022, 11, 11, 19, 19, 37, 573842, tzinfo=datetime.timezone.utc
                ),
                upload_to="images",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="profile",
            name="profile_pics",
            field=models.ImageField(upload_to="images"),
        ),
    ]
