# Generated by Django 4.1.3 on 2022-11-11 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "contactapp",
            "0005_alter_profile_address_alter_profile_contact_image_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="gender",
            field=models.CharField(
                choices=[("female", "female"), ("male", "male")],
                default="female",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
    ]
