# Generated by Django 4.1.3 on 2022-11-15 17:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("contactapp", "0006_profile_gender_alter_profile_address"),
    ]

    operations = [
        migrations.CreateModel(
            name="QrCode",
            fields=[
                (
                    "qr_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "qr_code",
                    models.ImageField(blank=True, null=True, upload_to="qr_codes"),
                ),
            ],
        ),
    ]
