# Generated by Django 4.1.3 on 2022-11-15 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contactapp", "0007_qrcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="qrcode",
            name="name",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
